# Generated by Django 5.2.4 on 2025-07-25 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sign_in_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': '"auth"."users"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.supabaseuser')),
                ('university', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
