# Generated by Django 5.2.4 on 2025-07-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SupabaseUser',
        ),
    ]
