# Generated by Django 5.2.4 on 2025-07-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='application',
        ),
        migrations.AlterModelTable(
            name='questionlist',
            table='question_list',
        ),
    ]
