# Generated by Django 5.2.4 on 2025-08-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='activity_name',
            field=models.CharField(default='Untitled', help_text='지원서 제목 (지원 활동명)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
