# Generated by Django 5.2.4 on 2025-08-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_activity_name_application_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='question_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
