# Generated by Django 5.2.4 on 2025-07-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_content_remove_activity_embedding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='activityembedding',
            old_name='user_id',
            new_name='user',
        ),
    ]
