# Generated by Django 5.2.4 on 2025-07-29 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_description_activity_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
