# Generated by Django 5.2.4 on 2025-07-29 15:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.TextField(help_text='활동 제목'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.TextField(blank=True, help_text='활동 카테고리', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, help_text='활동 설명', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='활동 종료일', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='favorite',
            field=models.BooleanField(default=False, help_text='즐겨찾기 여부'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='file_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='첨부파일 목록', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='키워드 목록', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='position',
            field=models.TextField(blank=True, help_text='활동 역할 및 직책', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='활동 시작일', null=True),
        ),
    ]
