# Generated by Django 5.2.4 on 2025-07-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_activity_name_alter_activity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_visit',
            field=models.DateTimeField(auto_now=True, help_text='마지막 방문일'),
        ),
    ]
