# Generated by Django 5.2.4 on 2025-07-31 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityembedding',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='activities.event'),
            preserve_default=False,
        ),
    ]
