# Generated by Django 5.2.4 on 2025-08-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activityembedding_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityembedding',
            name='content',
        ),
    ]
