# Generated by Django 5.2.4 on 2025-08-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_remove_activityembedding_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityembedding',
            name='favorite',
        ),
    ]
