# Generated by Django 5.2.4 on 2025-07-03 18:51

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_rename_user_id_activity_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
