# Generated by Django 5.2.4 on 2025-08-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='user_id',
            new_name='user',
        ),
    ]
