# Generated by Django 5.2.4 on 2025-08-13 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_questionlist_question_explanation'),
        ('chat', '0003_rename_user_id_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.questionlist'),
        ),
    ]
