# Generated by Django 5.2.4 on 2025-07-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_table_alter_questionlist_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questionlist',
            old_name='application_id',
            new_name='application',
        ),
    ]
