# Generated by Django 5.2.4 on 2025-07-25 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.questionlist')),
            ],
            options={
                'db_table': 'event_suggestion',
            },
        ),
    ]
