# Generated by Django 5.2.4 on 2025-07-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_aianalysis_table_alter_aisuggestion_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aianalysis',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='aisuggestion',
            old_name='question_id',
            new_name='question',
        ),
    ]
