# Generated by Django 5.2.4 on 2025-07-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.AlterModelTable(
            name='supabaseuser',
            table='"auth"."users"',
        ),
    ]
