name: Notify Slack on Push

on:
  push:
    branches:
      - '**'

jobs:
  slackNotify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 커밋 리스트 포맷팅
      - name: Format commit messages
        id: format
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

           # commit_count
          COMMIT_COUNT=$(echo '${{ toJson(github.event.commits) }}' | jq length)
          echo "commit_count=${COMMIT_COUNT}" >> $GITHUB_OUTPUT
          
          # commits: 한 줄에 한 커밋
          COMMITS=$(git log -n ${COMMIT_COUNT} --pretty=format:"%h %s - %an")
          ESCAPED_COMMITS=$(echo "$COMMITS" | jq -Rs .)
          echo "commits=${ESCAPED_COMMITS}" >> $GITHUB_OUTPUT
          
      # Slack 알림 전송
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          CLEAN_COMMITS=$(echo '${{ steps.format.outputs.commits }}' | jq -r .)

          JSON_PAYLOAD=$(
            echo '{
              "attachments": [
                {
                  "color": "#36a64f",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "[*['${{ steps.format.outputs.repo_name }}':'${BRANCH_NAME}']* '${{ steps.format.outputs.commit_count }}' new commits]"
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text":  "'"${CLEAN_COMMITS}"'"
                      }
                    }
                  ]
                }
              ]
            }'
          )
      
          echo "$JSON_PAYLOAD" | curl -X POST -H 'Content-type: application/json' --data @- $SLACK_WEBHOOK_URL
