name: Notify Slack on Push

on:
  push:
    branches:
      - '**'

jobs:
  slackNotify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 커밋 리스트 포맷팅
      - name: Format commit messages
        id: format
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

          # 커밋 개수 계산 (jq가 없으면 grep로 대체 가능)
          COMMIT_COUNT=$(echo '${{ toJson(github.event.commits) }}' | grep -o '{' | wc -l)
          echo "commit_count=$COMMIT_COUNT" >> $GITHUB_OUTPUT
          {
            echo "COMMITS<<EOF"
            git log -n ${COMMIT_COUNT} --pretty=format:"%h %s - %an"
            echo "EOF"
          } >> $GITHUB_OUTPUT
          
      # Slack 알림 전송
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"

          curl -X POST -H 'Content-type: application/json' --data "{
            \"attachments\": [
              {
                \"color\": \"#36a64f\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"[*[${{ steps.format.outputs.repo_name }}:${BRANCH_NAME}]* ${{ steps.format.outputs.commit_count }} new commits]\"
                    }
                  },
                  {
                    \"type\": \"divider\"
                  },
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"$(echo '${{ steps.format.outputs.COMMITS }}' | sed 's/^/`/' | sed 's/$/'\"'`'/)\"
                    }
                  }
                ]
              }
            ]
          }" $SLACK_WEBHOOK_URL
