name: Notify Slack on Push

on:
  push:
    branches:
      - '**'  

jobs:
  slackNotify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine commit count
        id: count
        run: echo "count=$(git rev-list --count HEAD ^HEAD~${{ github.event.commits && github.event.commits != null && fromJSON(toJSON(github.event.commits)) || '[]' }})" >> $GITHUB_OUTPUT

      - name: Format commit messages
        id: format
        env:
          COMMIT_COUNT: ${{ github.event.commits && github.event.commits != null && fromJSON(toJSON(github.event.commits)) && github.event.commits | size || 1 }}
        run: |
          echo "COMMITS<<EOF" >> $GITHUB_OUTPUT
          git log -n $COMMIT_COUNT --pretty=format:"• <%H|%h> %s - %an" --abbrev-commit | while read line; do
            COMMIT_HASH=$(echo "$line" | awk '{print $2}')
            COMMIT_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${COMMIT_HASH}"
            echo "$line" | sed "s|<%H|<${COMMIT_URL}|"
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          curl -X POST -H 'Content-type: application/json' --data "{
            \"blocks\": [
              {
                \"type\": \"section\",
                \"text\": {
                  \"type\": \"mrkdwn\",
                  \"text\": \":rocket: *[${{ github.repository }}:${BRANCH_NAME }]* — *${{ github.event.commits | length }} new commits pushed by ${{ github.actor }}*\"
                }
              },
              {
                \"type\": \"divider\"
              },
              {
                \"type\": \"section\",
                \"text\": {
                  \"type\": \"mrkdwn\",
                  \"text\": \"${{ steps.format.outputs.COMMITS }}\"
                }
              }
            ]
          }" $SLACK_WEBHOOK_URL
