name: Notify Slack on Push

on:
  push:
    branches:
      - '**'

jobs:
  slackNotify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 커밋 리스트 포맷팅
      - name: Format commit messages
        id: format
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

           # commit_count
          COMMIT_COUNT=$(echo '${{ toJson(github.event.commits) }}' | jq length)
          echo "commit_count=${COMMIT_COUNT}" >> $GITHUB_OUTPUT
          
          # commits: 한 줄에 한 커밋
          COMMITS=$(git log -n ${COMMIT_COUNT} --pretty=format:"• \`#%h\` %s - %an")
          #ESCAPED_COMMITS=$(echo "$COMMITS" | jq -Rs .)
          #echo "commits=${ESCAPED_COMMITS}" >> $GITHUB_OUTPUT
          # 멀티라인
          {
            echo "commits<<EOF"
            echo "$COMMITS"
            echo "EOF"
          } >> $GITHUB_OUTPUT
          
      # Slack 알림 전송
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          REPO_NAME="${{ steps.format.outputs.repo_name }}"
          COMMIT_COUNT="${{ steps.format.outputs.commit_count }}"
          CLEAN_COMMITS="${{ steps.format.outputs.commits }}"
      
          echo "=== Debug ==="
          echo "$CLEAN_COMMITS"
      
          jq -n \
            --arg repo "$REPO_NAME" \
            --arg branch "$BRANCH_NAME" \
            --arg commits "$CLEAN_COMMITS" \
            --arg count "$COMMIT_COUNT" \
            '{
              attachments: [
                {
                  color: "#36a64f",
                  blocks: [
                    {
                      type: "section",
                      text: {
                        type: "mrkdwn",
                        text: ":rocket:*[\($repo):\($branch)]* \($count) new commits"
                      }
                    },
                    {
                      type: "divider"
                    },
                    {
                      type: "section",
                      text: {
                        type: "mrkdwn",
                        text: $commits
                      }
                    }
                  ]
                }
              ]
            }' | curl -X POST -H 'Content-type: application/json' --data @- $SLACK_WEBHOOK_URL
